---
title: "metadata"
output: html_document
date: "2024-11-05"
---


Data used in the paper "Metabotypes of response to bariatric surgery independent of the magnitude of weight loss"

The data has been published in the paper web site and it also has an independent repository [https://github.com/nutrimetabolomics/Metabotyping2018](https://github.com/nutrimetabolomics/Metabotyping2018), which is mirrored here, so  **there is no need to access there**.

The dataset is formed by the following files :

- DataInfo_S013.csv: Metadata. Information on each column in the "DataValues_S013.csv" file.
- DataValues_S013.csv: Clinical and metabolomic values for 39 patients at 5 time points.
- AAInformation_S006.csv: Additional information on metabolites in the "DataValues_S013.csv" file.

El dataset está compuesto por 39 filas y 696 columnas. Las 39 filas representan 39 pacientes que han sido sometidos una de las siguientes cirugías: bypass o tubular. Encontramos información adicional sobre el género y la edad. Las demás columans representan distintos parámetros metabólicos que han sido tomados en 5 tiempos distintos.
